export const recipeCategories = [
  { value: 'breakfast', label: 'Śniadania' },
  { value: 'gluten-free', label: 'Bez glutenu' },
  { value: 'quick', label: 'Do 15 minut' },
  { value: '6m', label: 'Na początek' },
  { value: 'soup', label: 'Zupy' },
  { value: 'lunch', label: 'Obiady' },
  { value: 'milk-free', label: 'Bez mleka' },
  { value: '5-ingredients', label: 'Do 5 składników' },
  { value: '12m', label: 'Dla roczniaków' },
  { value: 'spread', label: 'Na chleb' },
  { value: 'dinner', label: 'Kolacje' },
  { value: 'eggs-free', label: 'Bez jajek' },
  { value: 'seasonal', label: 'Sezonowo' },
  { value: '24m', label: 'Dzieci +2' },
  { value: 'pancakes', label: 'Placuszki' },
  { value: 'desserts', label: 'Deserki' },
  { value: 'vegetarian', label: 'Wegetariańskie' },
  { value: 'snacks', label: 'Na spacer' },
  { value: 'school', label: 'Do szkoły' },
  { value: 'drink', label: 'Do picia' },
]
